# Układy równań liniowych

### Pojęcia warte poznania

* Układ równań liniowych: https://pl.wikipedia.org/wiki/Układ_równań_liniowych
* Rząd macierzy: https://pl.wikipedia.org/wiki/Rząd_macierzy
* Kombinacja liniowa: https://pl.wikipedia.org/wiki/Kombinacja_liniowa
* Eliminacja Gaussa: https://pl.wikipedia.org/wiki/Metoda_eliminacji_Gaussa, Kincaid-Cheney_*_ str. 245, pełny pseudokod: str. 252
* Pivoting: https://en.wikipedia.org/wiki/Pivot_element#Partial_and_complete_pivoting, K.C. str. 261, pełny pseudokod: str. 267
* Norma wektora: https://pl.wikipedia.org/wiki/Przestrze%C5%84_unormowana, K.C. str. 320
* Norma macierzy: https://pl.wikipedia.org/wiki/Norma_macierzowa
* Macierz dodatnio określona: https://pl.wikipedia.org/wiki/Określoność_formy
* Faktoryzacja LU: https://pl.wikipedia.org/wiki/Metoda_LU, K.C. str. 294
* Faktoryzacja Cholesky'ego: https://pl.wikipedia.org/wiki/Rozkład_Choleskiego, K.C. str. 305

Dodatkowo:
* Wskaźnik uwarunkowania: https://pl.wikipedia.org/wiki/Wska%C5%BAnik_uwarunkowania, K.C. str.321
* Metoda Jacobiego: https://en.wikipedia.org/wiki/Jacobi_method, K.C. 323

Książka dla wytrwałych (naprawdę): Y. Saad "Iterative Methods for Sparse Linear Systems"

In [2]:
from typing import Optional, Tuple
import numpy as np

### Zadanie rozgrzewkowe:
Napisać mnożenie macierzy w ulubionym_\**_ języku programowania.

**Pytanko:** jakie muszą być wymiary mnożonych macierzy? (Który wymiar musi się "zgadzać"?)

**Zadanko:** Uzupełnić brakujące wymiary macierzy w docstringu (z dokładnością do ["alfa-konwersji"](https://pl.wikipedia.org/wiki/Konwersja_α))

In [3]:
def agh_superfast_matrix_multiply(a: np.matrix, b: np.matrix) -> np.matrix:
    
    n = a.shape[0]
    m = a.shape[1]
    p = b.shape[1]
    c = np.zeros((n,p), dtype = int)
    
    for i in range(0,n):
        for j in range(0,p):
            for k in range(0,m):
                c[i,j] += a[i,k] * b[k,j]
    return c
    pass

m1 = np.matrix([[1, 2],
                [3, 4],
                [4, 5],
                [5, 1]])

m2 = np.matrix([[1, 2, 3],
                [4, 5, 6]])

res = agh_superfast_matrix_multiply(m1, m2)
print(res)
assert np.allclose(res, m1 * m2), "Wrong multiplication result"

[[ 9 12 15]
 [19 26 33]
 [24 33 42]
 [ 9 15 21]]


### Zadania
1. Przeczytać rozdz. 7. Kincaida i Cheney'a (Systems of Linear Equations).
2. Przeczytać rozdz. 8. Kincaida i Cheney'a (Additional Topics Concerning Systems of Linear Equations).
3. Napisać kod (w ulubionym_\**_ języku) do eliminacji Gaussa z i bez pivotingu.
4. Rozwiązać poniższy układ równań z pivotingiem i bez, porównać wyniki:

In [4]:
A = np.matrix([[0.0001, -5.0300, 5.8090, 7.8320],
               [2.2660, 1.9950,  1.2120, 8.0080],
               [8.8500, 5.6810,  4.5520, 1.3020],
               [6.7750, -2.253,  2.9080, 3.9700]])

b = np.matrix([9.5740, 7.2190, 5.7300, 6.2910]).transpose()

x = np.linalg.solve(A, b)

def gauss(a, b):
    
    n = len(a)
    res = np.zeros(n)
    
    for i in range(n):
        for j in range(i+1, n):
            m = a[j,i]/a[i,i]
            a[j,i] = m
            for k in range(i + 1, n):
                a[j,k] = a[j,k] - m*a[i,k]
            b[j] = b[j] - m*b[i]
            
    k = n-1
    res[k] = b[k]/a[k,k]
    while k >= 0:
        sum = b[k]
        for i in range(k+1,n):
            sum -= a[k,i]*res[i]
        res[k] = sum / a[k,k]
        k -= 1
    
    return np.matrix(res).transpose()

y = gauss(A, b)

assert np.allclose(x, y)

**Pytanie**: dlaczego wołamy `transpose()` na wektorze `b`?

Sprawdźmy, czy rozwiązanie jest ok (**Pytanie'**: dlaczego po prostu nie użyjemy `==` lub jakiegoś `equals`?):

In [ ]:
np.allclose(np.dot(A, x), b)

### Zadania, c.d.

5. Zaimplementować algorytm faktoryzacji LU macierzy
6. (*) Zaimplementować funkcję sprawdzającą, czy dana macierz jest symetryczna i dodatnio określona
7. Zaimplementować algorytm faktoryzacji Cholesky'ego macierzy

In [5]:
def agh_superfast_lu(a: np.matrix) -> Optional[Tuple[np.matrix, np.matrix]]:
    
    n = a.shape[0]
    up = np.zeros((n,n))
    low =  np.zeros((n,n))
    
    for i in range(0,n):
        low[i,i] = 1
        for j in range(i,n):
            sum = 0
            for k in range(0,i):
                sum += low[i,k]*up[k,j]
            up[i,j] = a[i,j] - sum
        for h in range(i+1,n):
            sum = 0
            for j in range(0,i):
                sum += low[h,j] * up[j,i]
            low[h, i] = (a[h, i] - sum) / up[i, i]
    
    return (low, up)

def agh_superfast_check_spd(a: np.matrix) -> bool:
    
    m = agh_superfast_cholesky(a)
    mt = agh_superfast_matrix_multiply(m, m.transpose())
    
    return np.allclose(mt, A)

def agh_superfast_cholesky(a: np.matrix) -> Optional[np.matrix]:
    
    n = len(a)
    l = np.zeros((n,n))
    
    for i in range(0,n):
        sum = 0
        for j in range(0,i):
            sum += l[i,j] * l[i,s]
        l[i,i] = pow(a[i,i] - sum, 1/2)
        for k in range(i+1, n):
            sum = 0
            for h in range(0,i):
                sum += l[k, h] * l[i, j]
            l[k, i] = (a[k, i] - sum) / l[i,i]
    
    return l

### Zadania, opcjonalnie
5. zaimplementować metodę Jacobiego (iteracyjne rozwiązywanie układu równań liniowych)
6. za pomocą tejże metody rozwiązać powyższy układ równań

\*  wszystkie referencje odnoszą się do [książki](https://wiki.iiet.pl/lib/exe/fetch.php?media=studia:przedmioty:mownit:numerical_mathematics_and_computing.pdf) David Kincaid, Ward Cheney - "Numerical Mathematics and Computing, 6th edition"
\** _ulubiony_ język programowania staramy się pojmować rozsądnie, tj. z wyłączeniem języków pokroju Prologa, języków z [tej listy](https://en.wikipedia.org/wiki/Esoteric_programming_language) oraz Assemblera i PHP. Haskella można używać na własną odpowiedzialność.